/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_soundtouchdemo_JNIMp3Encode */

#ifndef _Included_com_example_soundtouchdemo_JNIMp3Encode
#define _Included_com_example_soundtouchdemo_JNIMp3Encode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_soundtouchdemo_JNIMp3Encode
 * Method:    init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_soundtouchdemo_JNIMp3Encode_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_example_soundtouchdemo_JNIMp3Encode
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_soundtouchdemo_JNIMp3Encode_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_soundtouchdemo_JNIMp3Encode
 * Method:    encode
 * Signature: ([SI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_soundtouchdemo_JNIMp3Encode_encode
  (JNIEnv *, jobject, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
